import test from 'node:test';import assert from 'node:assert/strict';
import { taskDraft,updateProgress,overall,requireAdmin,expenseAmount,attendanceCount,date } from './domain.js';
const at='2026-09-17T10:00:00Z';const people={a:{name:'A',active:true},b:{name:'B',active:true}};const admin={id:'admin',role:'admin'},team={id:'a',role:'team'};
const input={title:'Prepare event',description:'',kind:'event',eventId:'event',start:'2026-09-17',deadline:'2026-09-20',priority:'High',assigneeIds:['a','b']};
test('employees cannot create assignments for others or change deadlines',()=>{assert.throws(()=>taskDraft(input,team,null,people,at));const own=taskDraft({...input,kind:'office',assigneeIds:['a']},team,null,people,at);assert.equal(own.eventId,'');assert.throws(()=>taskDraft({...input,deadline:'2026-10-01'},team,own,people,at));assert.throws(()=>requireAdmin(team));});
test('a group completes only when each assignee completes their own part',()=>{const task=taskDraft(input,admin,null,people,at);const first={...task,...updateProgress(task,'a','Complete',at)};assert.equal(first.status,'In progress');assert.equal(first.completedAt,null);assert.equal(first.progress.b.status,'To do');const last={...first,...updateProgress(first,'b','Complete',at)};assert.equal(last.status,'Complete');assert.equal(last.completedAt,at);assert.throws(()=>updateProgress(last,'a','To do',at));assert.throws(()=>updateProgress(task,'admin','Complete',at));});
test('admin deadline edits retain the original deadline and individual progress',()=>{const task=taskDraft(input,admin,null,people,at);const started={...task,...updateProgress(task,'a','Blocked',at)};const changed=taskDraft({...input,deadline:'2026-09-25'},admin,started,people,at);assert.equal(changed.originalDeadline,'2026-09-20');assert.equal(changed.status,'Blocked');assert.equal(changed.progress.a.status,'Blocked');});
test('dates, positive currency and attendance counts are validated',()=>{assert.throws(()=>date('2026-02-30','Date'));assert.throws(()=>taskDraft({...input,deadline:'2026-09-16'},admin,null,people,at));for(const n of [-1,0,1.1,NaN,Infinity])assert.throws(()=>expenseAmount(n));assert.equal(expenseAmount(12345),12345);for(const n of [-1,2.5,Infinity])assert.throws(()=>attendanceCount(n));assert.equal(attendanceCount(3),3);assert.equal(overall([],{}),'To do');});
test('inactive or empty teams and changed completed assignments are rejected',()=>{assert.throws(()=>taskDraft({...input,assigneeIds:[]},admin,null,people,at));assert.throws(()=>taskDraft(input,admin,null,{...people,b:{active:false}},at));const t=taskDraft(input,admin,null,people,at);t.status='Complete';assert.throws(()=>taskDraft({...input,assigneeIds:['a']},admin,t,people,at));});
