"use client";
import { useState,ReactNode } from 'react';
import { Loader2, UserPlus } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty } from '@/components/ui/combobox';
import { Member,EventRecord,Task,Client,Guest,today } from '@/lib/model';
import { mutate,friendlyError } from '@/lib/firebase';
import { Picker } from './ui';
import { toast } from 'sonner';
export type EditRequest={type:'task'|'event'|'client'|'guest'|'expense'|'member'|'review';id?:string;eventId?:string;kind?:string;walkIn?:boolean;assigneeIds?:string[]};
type Values={title:string;description:string;kind:string;eventId:string;start:string;deadline:string;priority:string;assigneeIds:string[];date:string;endDate:string;location:string;type:string;status:string;name:string;email:string;phone:string;company:string;department:string;password:string;accessRole:string;employeeType:string;clientId:string;invited:boolean;rsvp:string;attendance:number;amount:string;category:string;reviewKind:string;reviewText:string;newClient:boolean};
function Field({label,children}:{label:string;children:ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>;}
function employeeLabel(person:Member){const team=person.employeeType==='frontend'?'Frontend':person.employeeType==='backend'?'Backend':'';return [team,person.department||person.email].filter(Boolean).join(' · ');}
export function Editor({request,close,member,members,events,tasks,clients,guests,preview=false}:{request:EditRequest;close:()=>void;member:Member;members:Member[];events:EventRecord[];tasks:Task[];clients:Client[];guests:Guest[];preview?:boolean}){
 const task=tasks.find(x=>x.id===request.id),event=events.find(x=>x.id===request.id),client=clients.find(x=>x.id===request.id),guest=guests.find(x=>x.id===request.id);
 const [v,setV]=useState<Values>({title:'',description:'',kind:'office',eventId:request.eventId||(request.type==='expense'?'none':''),start:today(),deadline:today(),priority:'Medium',assigneeIds:request.assigneeIds||(member.role==='admin'?[]:[member.id]),date:today(),endDate:today(),location:'',type:'Client event',status:'Planning',name:'',email:'',phone:'',company:'',department:'',password:'',accessRole:'team',employeeType:'backend',clientId:'',invited:false,rsvp:'Pending',attendance:request.walkIn?1:0,amount:'',category:'Other',reviewKind:'Hit',reviewText:'',newClient:false,...(request.type==='task'&&task?task:{}),...(request.type==='event'&&event?event:{}),...(request.type==='client'&&client?client:{}),...(request.type==='guest'&&guest?guest:{})});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[createdClient,setCreatedClient]=useState('');
 const set=<K extends keyof Values>(key:K,value:Values[K])=>setV(old=>({...old,[key]:value}));
 const field=(label:string,key:keyof Values,type='text',required=true)=><Field label={label}><Input type={type} value={String(v[key])} required={required} onChange={e=>set(key,e.target.value as never)} maxLength={key==='password'?128:500} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} autoComplete={key==='password'?'new-password':undefined}/></Field>;
 const pick=(label:string,key:keyof Values,options:(string|{value:string;label:string})[])=><Field label={label}><Picker label={label} value={String(v[key])} onChange={s=>set(key,s as never)} options={options}/></Field>;
 const eventOptions=[{value:'none',label:'Office / general'},...events.map(e=>({value:e.id,label:e.title}))];
 async function save(e:React.FormEvent){e.preventDefault();if(preview)return;setBusy(true);setError('');try{
  if(request.type==='task'){if(!v.assigneeIds.length)throw new Error('Select at least one assignee.');await mutate('saveTask',{...(request.id?{id:request.id}:{}),title:v.title,description:v.description,kind:'office',eventId:'',assigneeIds:v.assigneeIds,start:v.start,deadline:v.deadline,priority:v.priority});}
  if(request.type==='event')await mutate('saveEvent',{...(request.id?{id:request.id}:{}),title:v.title,date:v.date,endDate:v.endDate,location:v.location,type:v.type,status:v.status,description:v.description});
  if(request.type==='client')await mutate('saveClient',{...(request.id?{id:request.id}:{}),name:v.name,company:v.company,email:v.email,phone:v.phone});
  if(request.type==='member')await mutate('addMember',{name:v.name,email:v.email,password:v.password,department:v.department,role:v.accessRole,employeeType:v.employeeType});
  if(request.type==='expense')await mutate('addExpense',{description:v.description,amountPaise:Math.round(Number(v.amount)*100),eventId:v.eventId==='none'?'':v.eventId,date:v.date,category:v.category});
  if(request.type==='review')await mutate('addReview',{eventId:v.eventId,kind:v.reviewKind,text:v.reviewText});
  if(request.type==='guest'){
   let clientId=v.clientId;
   if(v.newClient){if(createdClient)clientId=createdClient;else{const result=await mutate<{id:string}>('saveClient',{name:v.name,email:v.email,phone:v.phone,company:v.company});clientId=result.id;setCreatedClient(clientId);}}
   if(!clientId)throw new Error('Choose a client or add a new one.');
   await mutate('saveGuest',{eventId:v.eventId,clientId,invited:v.invited,rsvp:v.rsvp,attendance:Number(v.attendance)});
  }
  toast.success(request.id?'Changes saved':'Added to your workspace');close();
 }catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 const titles={task:request.id?'Edit task':'Create a task',event:request.id?'Edit event':'Plan a new event',client:request.id?'Edit client':'Add a client',guest:request.id?'Update guest':request.walkIn?'Add a walk-in':'Add event guest',expense:'Log an expense',member:'Add team member',review:'Add a hit or miss'};
 return <Dialog open onOpenChange={o=>{if(!o&&!busy)close();}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{titles[request.type]}</DialogTitle><DialogDescription>{preview?'Design preview — saving is disabled.':request.type==='member'?'Create an admin or employee login and choose the right team.':({task:'Set the work, deadline, and person responsible.',event:'Start with the event details. Add tasks and guests after saving.',client:'Save contact details once and reuse them for any event.',guest:'Record the invitation, response, or attendance for this guest.',expense:'Record an amount you paid for an event or the office.',review:'Share what went well or what the team can improve.'}[request.type])}</DialogDescription></DialogHeader><form onSubmit={save}><div className="editor-fields">
 {request.type==='task'&&<>{field('Task title','title')}<Field label="Description"><Textarea value={v.description} onChange={e=>set('description',e.target.value)} rows={3}/></Field><div className="form-grid">{field('Start date','start','date')}{field('Deadline','deadline','date')}</div>{pick('Priority','priority',['Low','Medium','High'])}{member.role==='admin'?<fieldset className="assignee-picker"><legend>Assign to employees <span>({v.assigneeIds.length} selected)</span></legend>{members.filter(m=>m.role==='team'&&(m.active||v.assigneeIds.includes(m.id))).map(m=><label key={m.id}><Checkbox checked={v.assigneeIds.includes(m.id)} disabled={!m.active||task?.status==='Complete'} onCheckedChange={checked=>set('assigneeIds',checked?[...v.assigneeIds,m.id]:v.assigneeIds.filter(id=>id!==m.id))}/><span>{m.name}<small>{employeeLabel(m)}{!m.active?' · Inactive':''}</small></span></label>)}{!members.some(m=>m.role==='team'&&m.active)&&<p>Add an active employee first.</p>}</fieldset>:<p className="form-note">Assigned to you. Your admin controls the deadline.</p>}</>}
 {request.type==='event'&&<>{field('Event name','title')}<div className="form-grid">{field('Start date','date','date')}{field('End date','endDate','date')}</div>{field('Venue / location','location','text',false)}<div className="form-grid">{pick('Event type','type',['Client event','Conference','Team gathering','Workshop','Other'])}{pick('Status','status',['Planning','Live','Complete'])}</div><Field label="Event brief"><Textarea value={v.description} onChange={e=>set('description',e.target.value)} rows={4}/></Field></>}
 {request.type==='client'&&<>{field('Client name','name')}{field('Company','company','text',false)}<div className="form-grid">{field('Email','email','email',false)}{field('Phone','phone','tel',false)}</div></>}
 {request.type==='member'&&<>{field('Full name','name')}{field('Work email','email','email')}{pick('Access level','accessRole',[{value:'team',label:'Employee'},{value:'admin',label:'Administrator'}])}{v.accessRole==='team'&&<><div className="form-grid">{pick('Employee team','employeeType',[{value:'frontend',label:'Frontend'},{value:'backend',label:'Backend'}])}{field('Department','department','text',false)}</div></>}{field('Temporary password (12+ characters)','password','password')}<p className="form-note">Employees manage their own task progress. Administrators can see the full team command board and assign work.</p></>}
 {request.type==='expense'&&<>{field('What was the expense for?','description')}<div className="form-grid">{field('Amount (₹ INR)','amount','number')}{field('Expense date','date','date')}</div>{pick('Event / office','eventId',eventOptions)}{pick('Category','category',['Travel','Food & beverage','Supplies','Venue','Other'])}<p className="form-note">Logged as paid by {member.name}. No receipt is required.</p></>}
 {request.type==='review'&&<>{pick('Type','reviewKind',['Hit','Miss'])}<Field label={v.reviewKind==='Hit'?'What went well?':'What could we improve?'}><Textarea required maxLength={4000} rows={5} value={v.reviewText} onChange={e=>set('reviewText',e.target.value)}/></Field></>}
 {request.type==='guest'&&<>{!request.id&&<><label className="check-label"><Checkbox checked={v.newClient} disabled={!!createdClient} onCheckedChange={c=>set('newClient',!!c)}/><UserPlus size={16}/> Add a new client to the directory</label>{v.newClient?<>{field('Client name','name')}{field('Company','company','text',false)}<div className="form-grid">{field('Phone','phone','tel',false)}{field('Email','email','email',false)}</div></>:<Field label="Find a client"><Combobox items={clients} value={clients.find(c=>c.id===v.clientId)||null} itemToStringLabel={(c:Client)=>c.name+' '+c.company} onValueChange={(c:Client|null)=>set('clientId',c?.id||'')}><ComboboxInput placeholder="Search clients…" aria-label="Search clients"/><ComboboxContent><ComboboxEmpty>No matching clients</ComboboxEmpty><ComboboxList>{(c:Client)=><ComboboxItem key={c.id} value={c}>{c.name}<span className="subtle">{c.company}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></Field>}</>}{request.id&&<p className="font-semibold">{clients.find(c=>c.id===v.clientId)?.name||'Client'}</p>}<label className="check-label"><Checkbox checked={v.invited} onCheckedChange={c=>set('invited',!!c)}/>Invitation sent manually</label>{pick('RSVP response','rsvp',['Pending','Yes','No','Maybe'])}<Field label="Number of people who attended"><Input type="number" min={0} max={1000} step={1} required value={v.attendance} onChange={e=>set('attendance',Number(e.target.value))}/></Field><p className="form-note">Use 0 for not checked in, 1 for the client alone, or the total including accompanying guests. Walk-ins do not need an invitation.</p></>}
 </div>{error&&<p role="alert" className="error-box">{error}</p>}<DialogFooter className="editor-footer"><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel</Button><Button type="submit" disabled={busy||preview}>{busy&&<Loader2 className="animate-spin"/>}{request.id?'Save changes':request.type==='expense'?'Log expense':request.type==='member'?'Create employee':'Add '+(request.type==='review'?'review':request.type)}</Button></DialogFooter></form></DialogContent></Dialog>;
}

