"use client";
import { useEffect,useState } from 'react';
import { ArrowUpRight, Sun, Moon, ArrowRight, Layers3, Loader2 } from 'lucide-react';
import { signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut, User } from 'firebase/auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { auth,mutate,friendlyError } from '@/lib/firebase';
export function Login({dark,toggle,user,accessError}:{dark:boolean;toggle:()=>void;user:User|null;accessError:string}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[setup,setSetup]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{if(setup){if(email.toLowerCase()!=='nrpcapital99@gmail.com')throw new Error('First-time setup is only for the designated admin email.');if(password.length<12)throw new Error('Use at least 12 characters.');await createUserWithEmailAndPassword(auth,email,password);await auth.currentUser?.getIdToken(true);await mutate('bootstrapAdmin');}else await signInWithEmailAndPassword(auth,email,password);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 useEffect(()=>{if(!user||user.email?.toLowerCase()!=='nrpcapital99@gmail.com')return;let cancelled=false;setBusy(true);setError('');mutate('bootstrapAdmin').catch(e=>{if(!cancelled)setError(friendlyError(e));}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[user]);
 async function reset(){if(!email){setError('Enter your email address first.');return;}setBusy(true);setError('');try{await sendPasswordResetEmail(auth,email);setMessage('If an account exists, password reset instructions have been sent.');}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 return <main className="login"><div className="login-story"><div className="brand"><span className="brand-mark">N</span><span>NRP <b>CAPITALS</b></span></div><div className="story-copy"><span className="eyebrow">PRODUCTIVITY PORTAL</span><h1>Clear work.<br/>Visible<br/><em>progress.</em></h1><p>One focused place for daily tasks,<br/>deadlines, and team updates.</p></div><div className="story-bottom"><Layers3 size={20}/><span>Tasks &nbsp; / &nbsp; Teams &nbsp; / &nbsp; Progress</span><ArrowUpRight size={22}/></div></div><div className="login-main"><Button className="theme-toggle" variant="outline" size="icon" aria-label="Toggle color theme" onClick={toggle}>{dark?<Sun/>:<Moon/>}</Button><div className="login-form"><span className="eyebrow">{user?'SIGNING IN':'LET’S GET TO WORK'}</span><h2>{user?'Opening your portal…':setup?'Create admin account':'Welcome back.'}</h2><p>{user?'This only takes a moment.':setup?'Set the email and password for the first admin.':'Use your email and password.'}</p>{user?<div className="access-panel"><Loader2 className={busy?'animate-spin':''} size={28}/><p className="mb-4">{user.email}</p>{user.email?.toLowerCase()!=='nrpcapital99@gmail.com'&&<p className="subtle">Ask your admin to add or reactivate your employee account.</p>}<Button variant="ghost" className="mt-3" onClick={()=>signOut(auth)}>Sign out</Button></div>:<form onSubmit={submit}><label>Email address<Input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@nrpcapitals.com" required/></label><label>Password<Input type="password" autoComplete={setup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder={setup?'At least 12 characters':'Enter your password'} minLength={setup?12:1} required/></label><Button disabled={busy} type="submit" className="login-submit">{setup?'Create admin account':'Sign in'}{busy?<Loader2 className="animate-spin" size={18}/>:<ArrowRight size={18}/>}</Button><div className="login-links"><button type="button" disabled={busy} onClick={reset}>Forgot password?</button><button type="button" disabled={busy} onClick={()=>{setSetup(!setup);setError('');setMessage('');}}>{setup?'Back to sign in':'First-time admin setup'}</button></div></form>}{(error||accessError)&&<p role="alert" className="error-box">{error||accessError}</p>}{message&&<p role="status" className="success-box">{message}</p>}<div className="login-help">Employee accounts are provided by your admin.</div></div><footer>NRP Capitals</footer></div></main>;
}
