"use client";

import { useState } from 'react';
import { ArrowUpRight, Check, MapPin, Pencil, Plus, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Client, EventRecord, Expense, Guest, Member, Task, completion, dateLabel, initials, money, timeLabel, count } from '@/lib/model';
import { Blank, Pager, Picker, SearchBox, Status, ViewMode, ViewToggle } from './ui';

const pageRows = <T,>(rows: T[], page: number) => rows.slice(page * 12, (page + 1) * 12);

export function EventBrowser({ events, tasks, guests, expenses, admin, open, create }: { events: EventRecord[]; tasks: Task[]; guests: Guest[]; expenses: Expense[]; admin: boolean; open: (id: string) => void; create: () => void }) {
  const [search, setSearch] = useState(''), [status, setStatus] = useState('All events'), [view, setView] = useState<ViewMode>('tiles'), [page, setPage] = useState(0);
  const rows = events.filter(event => (status === 'All events' || event.status === status) && [event.title, event.location, event.type].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a, b) => Number(a.status === 'Complete') - Number(b.status === 'Complete') || a.date.localeCompare(b.date));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 12) - 1)), visible = pageRows(rows, safePage);
  const facts = (event: EventRecord) => { const eventTasks = tasks.filter(task => task.eventId === event.id), eventGuests = guests.filter(guest => guest.eventId === event.id), percent = eventTasks.length ? Math.round(eventTasks.reduce((sum, task) => sum + completion(task), 0) / eventTasks.length) : 0; return { eventTasks, eventGuests, percent }; };
  return <section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setPage(0); }} placeholder="Search events…"/><div className="filters"><Picker value={status} onChange={value => { setStatus(value); setPage(0); }} label="Event status" options={['All events', 'Planning', 'Live', 'Complete']}/><ViewToggle value={view} onChange={setView}/></div></div>{visible.length ? <>{view === 'tiles' ? <div className="record-grid event-card-grid">{visible.map(event => { const { eventTasks, eventGuests, percent } = facts(event); return <button className="record-card event-card" key={event.id} onClick={() => open(event.id)}><div className="card-heading"><Status value={event.status}/><span>{dateLabel(event.date)}</span></div><h3>{event.title}</h3><p><MapPin size={14}/>{event.location || 'Location to be confirmed'}</p><div className="card-progress"><span>{eventTasks.filter(task => task.status === 'Complete').length} of {eventTasks.length} tasks complete</span><Progress value={percent}/></div><div className="card-footer"><span>{eventGuests.filter(guest => guest.rsvp === 'Yes').length} confirmed</span>{admin && <strong>{money(expenses.filter(expense => expense.eventId === event.id).reduce((sum, expense) => sum + expense.amountPaise, 0))}</strong>}</div></button>; })}</div> : <Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Date</TableHead><TableHead>Status</TableHead><TableHead>Progress</TableHead><TableHead>Guests</TableHead>{admin && <TableHead>Expenses</TableHead>}<TableHead/></TableRow></TableHeader><TableBody>{visible.map(event => { const { eventTasks, eventGuests, percent } = facts(event); return <TableRow key={event.id}><TableCell><button className="row-title" onClick={() => open(event.id)}>{event.title}</button><span className="row-subtitle"><MapPin size={12}/>{event.location || 'Location to be confirmed'}</span></TableCell><TableCell>{dateLabel(event.date)}</TableCell><TableCell><Status value={event.status}/></TableCell><TableCell><div className="task-progress"><Progress value={percent}/><span>{percent}%</span></div></TableCell><TableCell>{eventGuests.filter(guest => guest.rsvp === 'Yes').length} confirmed</TableCell>{admin && <TableCell>{money(expenses.filter(expense => expense.eventId === event.id).reduce((sum, expense) => sum + expense.amountPaise, 0))}</TableCell>}<TableCell><Button variant="ghost" size="icon" aria-label={'Open ' + event.title} onClick={() => open(event.id)}><ArrowUpRight size={18}/></Button></TableCell></TableRow>; })}</TableBody></Table>}<Pager page={safePage} total={rows.length} onChange={setPage}/></> : <Blank title={events.length ? 'No matching events' : 'No events yet'} description={events.length ? 'Try a different search or status.' : 'Create an event to manage its work, guests, and costs.'} action={admin && <Button onClick={create}><Plus size={16}/>New event</Button>}/>}</section>;
}

export function ExpenseBrowser({ expenses, events }: { expenses: Expense[]; events: EventRecord[] }) {
  const [search, setSearch] = useState(''), [view, setView] = useState<ViewMode>('tiles'), [page, setPage] = useState(0);
  const rows = expenses.filter(expense => [expense.description, expense.paidByName, expense.category, events.find(event => event.id === expense.eventId)?.title].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 12) - 1)), visible = pageRows(rows, safePage);
  return <section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setPage(0); }} placeholder="Search expenses…"/><div className="filters"><span className="result-count">{count(rows.length, 'entry', 'entries')} · {money(rows.reduce((sum, expense) => sum + expense.amountPaise, 0))}</span><ViewToggle value={view} onChange={setView}/></div></div>{visible.length ? <>{view === 'tiles' ? <div className="record-grid">{visible.map(expense => <article className="record-card" key={expense.id}><div className="card-heading"><Status value={expense.category}/><strong>{money(expense.amountPaise)}</strong></div><h3>{expense.description}</h3><p>{events.find(event => event.id === expense.eventId)?.title || 'Office / general'}</p><div className="card-footer"><span>{expense.paidByName}</span><strong>{dateLabel(expense.date)}</strong></div></article>)}</div> : <Table><TableHeader><TableRow><TableHead>Expense</TableHead><TableHead>Paid by</TableHead><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader><TableBody>{visible.map(expense => <TableRow key={expense.id}><TableCell><strong>{expense.description}</strong><span className="row-subtitle">{events.find(event => event.id === expense.eventId)?.title || 'Office / general'}</span></TableCell><TableCell>{expense.paidByName}</TableCell><TableCell>{dateLabel(expense.date)}</TableCell><TableCell><Status value={expense.category}/></TableCell><TableCell className="text-right font-semibold">{money(expense.amountPaise)}</TableCell></TableRow>)}</TableBody></Table>}<Pager page={safePage} total={rows.length} onChange={setPage}/></> : <Blank title="No expenses found" description={expenses.length ? 'Try another search.' : 'Logged expenses will appear here.'}/>}</section>;
}

export function GuestBrowser({ guests, clients, edit, add }: { guests: Guest[]; clients: Client[]; edit: (id: string) => void; add: (walkIn: boolean) => void }) {
  const [search, setSearch] = useState(''), [stage, setStage] = useState('All'), [view, setView] = useState<ViewMode>('tiles'), [page, setPage] = useState(0);
  const stages = [{ title: 'All', count: guests.length }, { title: 'Invited', count: guests.filter(guest => guest.invited).length }, { title: 'RSVP', count: guests.filter(guest => guest.rsvp !== 'Pending').length }, { title: 'Attended', count: guests.reduce((sum, guest) => sum + guest.attendance, 0) }];
  const rows = guests.filter(guest => (stage === 'All' || (stage === 'Invited' ? guest.invited : stage === 'RSVP' ? guest.rsvp !== 'Pending' : guest.attendance > 0)) && [clients.find(client => client.id === guest.clientId)?.name, clients.find(client => client.id === guest.clientId)?.company, clients.find(client => client.id === guest.clientId)?.phone, clients.find(client => client.id === guest.clientId)?.email].join(' ').toLowerCase().includes(search.toLowerCase()));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 12) - 1)), visible = pageRows(rows, safePage);
  return <><div className="guest-pipeline">{stages.map(item => <button key={item.title} className={stage === item.title ? 'active' : ''} onClick={() => { setStage(item.title); setPage(0); }}><strong>{item.count}</strong><span>{item.title}</span></button>)}</div><section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setPage(0); }} placeholder="Search guests…"/><div className="filters"><ViewToggle value={view} onChange={setView}/><Button variant="outline" onClick={() => add(true)}><UserPlus size={16}/>Walk-in</Button><Button onClick={() => add(false)}><Plus size={16}/>Add guest</Button></div></div>{visible.length ? <>{view === 'tiles' ? <div className="record-grid">{visible.map(guest => { const client = clients.find(item => item.id === guest.clientId); return <article className="record-card" key={guest.id}><div className="card-heading"><Status value={guest.rsvp}/>{guest.walkIn && <span className="mini-label">Walk-in</span>}</div><h3>{client?.name || 'Client unavailable'}</h3><p>{client?.company || client?.email || 'No contact details'}</p><div className="card-tags"><Status value={guest.invited ? 'Invited' : 'Not sent'}/>{guest.attendance > 0 && <span className="success-inline"><Check size={14}/>{guest.attendance} attended</span>}</div><div className="card-footer"><span>{guest.attendedAt ? timeLabel(guest.attendedAt) : 'Not checked in'}</span><Button variant="outline" size="sm" onClick={() => edit(guest.id)}>Update</Button></div></article>; })}</div> : <Table><TableHeader><TableRow><TableHead>Guest</TableHead><TableHead>Contact</TableHead><TableHead>Invitation</TableHead><TableHead>RSVP</TableHead><TableHead>Attendance</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map(guest => { const client = clients.find(item => item.id === guest.clientId); return <TableRow key={guest.id}><TableCell><strong>{client?.name || 'Client unavailable'}</strong><span className="row-subtitle">{client?.company}{guest.walkIn && ' · Walk-in'}</span></TableCell><TableCell>{client?.phone || client?.email || '—'}</TableCell><TableCell><Status value={guest.invited ? 'Invited' : 'Not sent'}/></TableCell><TableCell><Status value={guest.rsvp}/></TableCell><TableCell>{guest.attendance > 0 ? guest.attendance + ' attended' : 'Not checked in'}</TableCell><TableCell><Button variant="outline" size="sm" onClick={() => edit(guest.id)}>Update</Button></TableCell></TableRow>; })}</TableBody></Table>}<Pager page={safePage} total={rows.length} onChange={setPage}/></> : <Blank title="No guests found" description={guests.length ? 'Try another search or stage.' : 'Add a client or a walk-in to this event.'}/>}</section></>;
}

export function ClientBrowser({ clients, guests, admin, edit }: { clients: Client[]; guests: Guest[]; admin: boolean; edit: (id: string) => void }) {
  const [search, setSearch] = useState(''), [view, setView] = useState<ViewMode>('tiles'), [page, setPage] = useState(0);
  const rows = clients.filter(client => [client.name, client.email, client.phone, client.company].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a, b) => a.name.localeCompare(b.name));
  const safePage = Math.min(page, Math.max(0, Math.ceil(rows.length / 12) - 1)), visible = pageRows(rows, safePage);
  return <section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={value => { setSearch(value); setPage(0); }} placeholder="Search clients…"/><div className="filters"><span className="result-count">{count(rows.length, 'client')}</span><ViewToggle value={view} onChange={setView}/></div></div>{visible.length ? <>{view === 'tiles' ? <div className="record-grid">{visible.map(client => <article className="record-card person-card" key={client.id}><div className="person-card-heading"><span className="avatar">{initials(client.name)}</span><div><h3>{client.name}</h3><p>{client.company || 'No company'}</p></div>{admin && <Button variant="ghost" size="icon" aria-label={'Edit ' + client.name} onClick={() => edit(client.id)}><Pencil size={16}/></Button>}</div><dl><div><dt>Email</dt><dd>{client.email || '—'}</dd></div><div><dt>Phone</dt><dd>{client.phone || '—'}</dd></div><div><dt>Events</dt><dd>{guests.filter(guest => guest.clientId === client.id).length}</dd></div></dl></article>)}</div> : <Table><TableHeader><TableRow><TableHead>Client</TableHead><TableHead>Company</TableHead><TableHead>Email</TableHead><TableHead>Phone</TableHead><TableHead>Events</TableHead>{admin && <TableHead/>}</TableRow></TableHeader><TableBody>{visible.map(client => <TableRow key={client.id}><TableCell><div className="client-name"><span className="avatar">{initials(client.name)}</span><strong>{client.name}</strong></div></TableCell><TableCell>{client.company || '—'}</TableCell><TableCell>{client.email || '—'}</TableCell><TableCell>{client.phone || '—'}</TableCell><TableCell>{guests.filter(guest => guest.clientId === client.id).length}</TableCell>{admin && <TableCell><Button variant="ghost" size="icon" aria-label={'Edit ' + client.name} onClick={() => edit(client.id)}><Pencil size={16}/></Button></TableCell>}</TableRow>)}</TableBody></Table>}<Pager page={safePage} total={rows.length} onChange={setPage}/></> : <Blank title="No clients found" description={clients.length ? 'Try another search.' : 'Add a client once and reuse their details across events.'}/>}</section>;
}

export function PeopleBrowser({ members, tasks, changeAccess }: { members: Member[]; tasks: Task[]; changeAccess: (member: Member) => void }) {
  const [search, setSearch] = useState(''), [view, setView] = useState<ViewMode>('tiles');
  const rows = members.filter(member => [member.name, member.email, member.department].join(' ').toLowerCase().includes(search.toLowerCase()));
  const metrics = (member: Member) => ({ open: tasks.filter(task => task.assigneeIds.includes(member.id) && task.progress[member.id]?.status !== 'Complete').length, done: tasks.filter(task => task.progress[member.id]?.status === 'Complete').length });
  return <section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search team…"/><div className="filters"><span className="result-count">{count(rows.length, 'member')}</span><ViewToggle value={view} onChange={setView}/></div></div>{view === 'tiles' ? <div className="record-grid">{rows.map(member => { const { open, done } = metrics(member); return <article className="record-card person-card" key={member.id}><div className="person-card-heading"><span className="avatar">{initials(member.name)}</span><div><h3>{member.name}</h3><p>{member.department || member.email}</p></div><Status value={member.active ? 'Active' : 'Inactive'}/></div><dl><div><dt>Role</dt><dd>{member.role === 'admin' ? 'Admin' : 'Team member'}</dd></div><div><dt>Open</dt><dd>{open}</dd></div><div><dt>Completed</dt><dd>{done}</dd></div></dl>{member.role !== 'admin' && <Button variant="outline" size="sm" onClick={() => changeAccess(member)}>{member.active ? 'Deactivate' : 'Reactivate'}</Button>}</article>; })}</div> : <Table><TableHeader><TableRow><TableHead>Team member</TableHead><TableHead>Department</TableHead><TableHead>Access</TableHead><TableHead>Open</TableHead><TableHead>Completed</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map(member => { const { open, done } = metrics(member); return <TableRow key={member.id}><TableCell><div className="client-name"><span className="avatar">{initials(member.name)}</span><div><strong>{member.name}</strong><span className="row-subtitle">{member.email}</span></div></div></TableCell><TableCell>{member.department || '—'}</TableCell><TableCell><Status value={member.active ? 'Active' : 'Inactive'}/></TableCell><TableCell>{open}</TableCell><TableCell>{done}</TableCell><TableCell>{member.role !== 'admin' && <Button variant="outline" size="sm" onClick={() => changeAccess(member)}>{member.active ? 'Deactivate' : 'Reactivate'}</Button>}</TableCell></TableRow>; })}</TableBody></Table>}</section>;
}
