"use client";
import { ReactNode,useState } from 'react';
import { Search, Check, Circle, Clock3, CircleAlert, ArrowUpRight, Users, ListTodo, ChevronLeft, ChevronRight } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Progress } from '@/components/ui/progress';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia } from '@/components/ui/empty';
import { Pagination,PaginationContent,PaginationItem } from '@/components/ui/pagination';
import { Task,EventRecord,completion,dateLabel,initials,overdue } from '@/lib/model';
export function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value,l=typeof o==='string'?o:o.label;return <SelectItem key={v} value={v}>{l}</SelectItem>;})}</SelectContent></Select>;}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search-box"><Search size={17}/><Input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
export function Status({value}:{value:string}){const type=['Complete','Yes','Active','Hit'].includes(value)?'green':['Blocked','No','Overdue','Miss','Inactive'].includes(value)?'red':['In progress','Live','Invited'].includes(value)?'blue':['Maybe','High','Pending'].includes(value)?'amber':'neutral';const Icon=value==='Complete'?Check:value==='Blocked'||value==='Overdue'?CircleAlert:value==='In progress'?Clock3:Circle;return <span className={'status '+type}><Icon size={12}/>{value}</span>;}
export function Avatars({names}:{names:string[]}){return <div className="avatar-stack" aria-label={names.join(', ')}>{names.slice(0,4).map((n,i)=><span key={n+i} className={'avatar tone-'+i} title={n}>{initials(n)}</span>)}{names.length>4&&<span className="avatar">+{names.length-4}</span>}</div>;}
export function Blank({title,description,action}:{title:string;description:string;action?:ReactNode}){return <Empty className="blank"><EmptyHeader><EmptyMedia variant="icon"><ListTodo/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{action}</Empty>;}
export function PageTitle({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:ReactNode}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="title-actions">{actions}</div></div>;}
export function Stat({label,value,detail,icon,tone=''}:{label:string;value:string|number;detail:string;icon:ReactNode;tone?:string}){return <div className={'stat '+tone}><div className="stat-top"><span>{label}</span>{icon}</div><strong>{value}</strong><p>{detail}</p></div>;}
export function Pager({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}){return <div className="table-footer"><span>{total===0?'0':Math.min(page*12+1,total)}–{Math.min((page+1)*12,total)} of {total}</span><Pagination className="m-0 w-auto"><PaginationContent><PaginationItem><Button variant="outline" size="icon" aria-label="Previous page" disabled={page===0} onClick={()=>onChange(page-1)}><ChevronLeft/></Button></PaginationItem><PaginationItem><Button variant="outline" size="icon" aria-label="Next page" disabled={(page+1)*12>=total} onClick={()=>onChange(page+1)}><ChevronRight/></Button></PaginationItem></PaginationContent></Pagination></div>;}
export function TaskTable({tasks,events,onOpen,compact=false}:{tasks:Task[];events:EventRecord[];onOpen:(t:Task)=>void;compact?:boolean}){
 const [search,setSearch]=useState(''),[status,setStatus]=useState('All statuses'),[owner,setOwner]=useState('all'),[page,setPage]=useState(0);
 const people=Object.fromEntries(tasks.flatMap(t=>Object.entries(t.assigneeNames)));
 const rows=tasks.filter(t=>(status==='All statuses'||(status==='Overdue'?overdue(t):t.status===status))&&(owner==='all'||t.assigneeIds.includes(owner))&&[t.title,t.description,...Object.values(t.assigneeNames),events.find(e=>e.id===t.eventId)?.title].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(a.status==='Complete')-Number(b.status==='Complete')||a.deadline.localeCompare(b.deadline));
 const safePage=Math.min(page,Math.max(0,Math.ceil(rows.length/12)-1));
 return <section className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={s=>{setSearch(s);setPage(0);}} placeholder="Search tasks or people…"/><div className="filters"><Picker label="Task status" value={status} onChange={v=>{setStatus(v);setPage(0);}} options={['All statuses','To do','In progress','Blocked','Complete','Overdue']}/>{!compact&&<Picker label="Assignee filter" value={owner} onChange={v=>{setOwner(v);setPage(0);}} options={[{value:'all',label:'All people'},...Object.entries(people).map(([value,label])=>({value,label}))]}/>}</div></div>{rows.length?<><Table><TableHeader><TableRow><TableHead>Task / responsibility</TableHead><TableHead>Assignees</TableHead><TableHead>Status</TableHead><TableHead>Deadline</TableHead><TableHead>Progress</TableHead><TableHead><span className="sr-only">Open</span></TableHead></TableRow></TableHeader><TableBody>{rows.slice(safePage*12,(safePage+1)*12).map(t=><TableRow key={t.id}><TableCell><button className="row-title" onClick={()=>onOpen(t)}>{t.title}</button><span className="row-subtitle">{events.find(e=>e.id===t.eventId)?.title||'Office task'} <span className={'priority '+t.priority.toLowerCase()}>{t.priority}</span></span></TableCell><TableCell><Avatars names={Object.values(t.assigneeNames)}/><span className="row-subtitle">{t.assigneeIds.length===1?Object.values(t.assigneeNames)[0]:t.assigneeIds.length+' people'}</span></TableCell><TableCell><Status value={t.status}/></TableCell><TableCell><span className={overdue(t)?'text-destructive':''}>{dateLabel(t.deadline)}</span>{overdue(t)&&<span className="row-subtitle text-destructive">Overdue</span>}</TableCell><TableCell><div className="task-progress"><Progress value={completion(t)}/><span>{completion(t)}%</span></div></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={'Open '+t.title} onClick={()=>onOpen(t)}><ArrowUpRight size={18}/></Button></TableCell></TableRow>)}</TableBody></Table><Pager page={safePage} total={rows.length} onChange={setPage}/></>:<Blank title={tasks.length?'No matching tasks':'A clear start.'} description={tasks.length?'Try another search or filter.':'New assignments will appear here with owners, deadlines, and progress.'}/>}</section>;
}
export function Gantt({tasks,onOpen}:{tasks:Task[];onOpen:(t:Task)=>void}){
 const [search,setSearch]=useState(''),[zoom,setZoom]=useState('Week');
 const rows=tasks.filter(t=>[t.title,...Object.values(t.assigneeNames)].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.start.localeCompare(b.start));
 if(!tasks.length)return <div className="panel"><Blank title="Your timeline starts here" description="Add tasks with start dates and deadlines to map the event schedule."/></div>;
 const day=86400000,parse=(s:string)=>Date.parse(s+'T00:00:00Z'),min=Math.min(...tasks.map(t=>parse(t.start))),max=Math.max(...tasks.map(t=>parse(t.deadline))),unit=zoom==='Day'?day:7*day,width=zoom==='Day'?46:112,total=Math.max(4,Math.ceil((max-min+day)/unit)),canvas=total*width;
 return <div className="panel"><div className="panel-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search timeline…"/><Picker label="Timeline scale" value={zoom} onChange={setZoom} options={['Day','Week']}/></div><div className="gantt-scroll"><div style={{minWidth:canvas+260}}><div className="gantt-header"><div className="gantt-label">TASK & OWNER</div><div className="gantt-axis" style={{width:canvas}}>{Array.from({length:total},(_,i)=><span key={i} style={{width}}>{new Date(min+i*unit).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'UTC'})}</span>)}</div></div>{rows.map(t=><div className="gantt-row" key={t.id}><button className="gantt-label" onClick={()=>onOpen(t)}><strong>{t.title}</strong><span>{Object.values(t.assigneeNames).join(', ')}</span></button><div className="gantt-track" style={{width:canvas,backgroundSize:width+'px 100%'}}><button aria-label={t.title+', '+dateLabel(t.start)+' to '+dateLabel(t.deadline)+', '+t.status} className={'gantt-bar '+(t.status==='Complete'?'done':overdue(t)?'late':'')} style={{left:(parse(t.start)-min)/unit*width,width:Math.max(24,(parse(t.deadline)-parse(t.start)+day)/unit*width)}} onClick={()=>onOpen(t)}><span style={{width:completion(t)+'%'}}/><b>{completion(t)}%</b></button></div></div>)}</div></div><div className="gantt-legend"><span><i/>Scheduled</span><span><i className="green"/>Complete</span><span><i className="red"/>Overdue</span><span>Dates in IST · Select a bar for task details</span></div></div>;
}


