import type { PreviewData } from '@/app/workspace';
import type { Member,Task,EventRecord,Client,Expense,Guest,Review,ProgressStatus } from './model';
import { today } from './model';
export function createPreview(mode:string):PreviewData{
const date=(offset:number)=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);},at=new Date().toISOString();
const members:Member[]=[{id:'admin',name:'NRP Admin',email:'admin@example.test',role:'admin',active:true,department:'Administration',createdAt:at},...['Ananya Shah','Rohan Mehta','Priya Kapoor','Arjun Rao'].map((name,i)=>({id:'p'+i,name,email:'person'+i+'@example.test',role:'team' as const,active:true,department:['Client relations','Operations','Marketing','Finance'][i],createdAt:at}))];
const events:EventRecord[]=[{id:'e1',title:'Annual Investor Connect',date:date(10),endDate:date(10),location:'The Grand Ballroom, Mumbai',type:'Client event',status:'Planning',description:'An evening of meaningful conversations, market perspectives, and stronger relationships.',createdAt:at},{id:'e2',title:'Founders Roundtable',date:date(18),endDate:date(18),location:'NRP Capitals · Boardroom',type:'Conference',status:'Planning',description:'A focused conversation with our founder community.',createdAt:at},{id:'e3',title:'Quarterly Team Summit',date:date(-3),endDate:date(-3),location:'NRP Capitals · Office',type:'Team gathering',status:'Complete',description:'Reflect, reconnect, and plan for the quarter ahead.',createdAt:at}];
const make=(id:string,title:string,eventId:string,ids:string[],statuses:ProgressStatus[],deadline:number,kind:'office'|'event'|'responsibility'='event'):Task=>({id,title,description:'Coordinate the details, keep the team informed, and post updates as work progresses.',eventId,kind,start:date(-7),deadline:date(deadline),originalDeadline:date(deadline),priority:deadline<0?'High':'Medium',assigneeIds:ids,assigneeNames:Object.fromEntries(ids.map(id=>[id,members.find(m=>m.id===id)!.name])),progress:Object.fromEntries(ids.map((id,i)=>[id,{status:statuses[i],updatedAt:at,completedAt:statuses[i]==='Complete'?at:null}])),status:statuses.every(x=>x==='Complete')?'Complete':statuses.includes('Blocked')?'Blocked':statuses.some(x=>x!=='To do')?'In progress':'To do',createdBy:'admin',createdAt:at,updatedAt:at,completedAt:statuses.every(x=>x==='Complete')?at:null});
const tasks:Task[]=[make('t1','Finalize venue & catering','e1',['p1','p3'],['In progress','Complete'],2),make('t2','Prepare the client shortlist','e1',['p0','p2'],['Complete','Complete'],-1),make('t3','Confirm the guest speakers','e1',['p0'],['Blocked'],-2),make('t4','Design event collateral','e1',['p2'],['In progress'],4),make('t5','Guest welcome & check-in','e1',['p0','p1'],['To do','To do'],10,'responsibility'),make('t6','Finalize discussion agenda','e2',['p0','p2'],['In progress','To do'],9),make('t7','Close monthly expense records','',['p3'],['In progress'],3,'office'),make('t8','Update client contact details','',['p0'],['To do'],1,'office'),make('t9','Prepare the weekly operations report','',['p1'],['Blocked'],-1,'office'),make('t10','Review quarterly communications','',['p2'],['Complete'],-2,'office')];
const clients:Client[]=['Aarav Desai','Meera Joshi','Vikram Sethi','Isha Malhotra','Kabir Nair','Tara Bhat'].map((name,i)=>({id:'c'+i,name,company:['Meridian Ventures','Northstar Group','Cedar Partners','Westbridge Studio','Atlas Industries','Horizon Advisory'][i],phone:'',email:'guest'+i+'@example.test',createdAt:at}));
const guests:Guest[]=clients.map((c,i)=>({id:'e1_'+c.id,eventId:'e1',clientId:c.id,invited:i!==5,rsvp:i<3?'Yes':i===3?'Maybe':'Pending',attendance:0,attendedAt:null,walkIn:false,updatedAt:at}));
const expenses:Expense[]=[{id:'x1',eventId:'e1',description:'Venue coordination travel',amountPaise:245000,date:date(-2),category:'Travel',paidBy:'p1',paidByName:'Rohan Mehta',createdAt:at},{id:'x2',eventId:'e1',description:'Printed event stationery',amountPaise:680000,date:date(-1),category:'Supplies',paidBy:'p2',paidByName:'Priya Kapoor',createdAt:at},{id:'x3',eventId:'e2',description:'Roundtable refreshments',amountPaise:325000,date:date(0),category:'Food & beverage',paidBy:'p0',paidByName:'Ananya Shah',createdAt:at}];
const reviews:Review[]=[{id:'r1',eventId:'e3',kind:'Hit',text:'Smaller discussion groups gave everyone the space to contribute.',authorId:'p0',authorName:'Ananya Shah',createdAt:at},{id:'r2',eventId:'e3',kind:'Miss',text:'Allow more time between the sessions for informal conversations.',authorId:'p1',authorName:'Rohan Mehta',createdAt:at}];
return {member:mode==='team'?members[1]:members[0],members:mode==='team'?[members[1]]:members,events,tasks:mode==='team'?tasks.filter(t=>t.assigneeIds.includes('p0')):tasks,clients,guests,expenses:mode==='team'?expenses.filter(e=>e.paidBy==='p0'):expenses,reviews};
}

